window.VT_PRODUCTS = {
  "p1": {
    "id": "p1",
    "name": "Camera Dome 2MP",
    "price": 1010000,
    "description": "Camera Dome 2MP — mô tả ngắn cho sản phẩm Camera Dome 2MP.",
    "image": "Camera/Camera ip 2mp hikvision DS-2CD1327G2-LUF.png",
     "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P1",
    "warranty": "12 tháng",
    "category": "Camera & CCTV"
  },
  "p2": {
    "id": "p2",
    "name": "Camera Bullet 4MP",
    "price": 1020000,
    "description": "Camera Bullet 4MP — mô tả ngắn cho sản phẩm Camera Bullet 4MP.",
    "image": "Camera/DS-2CD1T27GO-LUF.png",
     "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P2",
    "warranty": "12 tháng",
    "category": "Camera & CCTV"
  },
  "p3": {
    "id": "p3",
    "name": "Camera 4G ngoài trời 3MP",
    "price": 1030000,
    "description": "Camera 4G ngoài trời 3MP — mô tả ngắn cho sản phẩm Camera 4G ngoài trời 3MP.",
    "image": "Camera/ipc-s7up-11m0wed-1.webp",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P3",
    "warranty": "12 tháng",
    "category": "Camera & CCTV"
  },
  "p4": {
    "id": "p4",
    "name": "Camera POV PTZ 2MP",
    "price": 1040000,
    "description": "Camera POV PTZ 2MP — mô tả ngắn cho sản phẩm Camera POV PTZ 2MP.",
    "image": "Camera/Camera IMOU IPC-S7DP-5M0WEZ 5MP(Cruiser Z 3K).png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P4",
    "warranty": "12 tháng",
    "category": "Camera & CCTV"
  },
  "p5": {
    "id": "p5",
    "name": "Camera Mini 2MP",
    "price": 150000,
    "description": "Camera Mini 2MP — mô tả ngắn cho sản phẩm Camera Mini 2MP.",
    "image": "Camera/Camera IPC-S2VBP-5M0WR (Rex VT Pro 3K).png",
    "sku": "SKU-P5",
    "warranty": "12 tháng",
    "category": "Camera & CCTV"
  },
  "p6": {
    "id": "p6",
    "name": "NVR 8 kênh",
    "price": 1060000,
    "description": "NVR 8 kênh — mô tả ngắn cho sản phẩm NVR 8 kênh.",
    "image": "Camera/Camera IPC-K2MP-3H1WE (Ranger Mini, 3MP).png",
    "sku": "SKU-P6",
    "warranty": "12 tháng",
    "category": "Camera & CCTV"
  },
  "p7": {
    "id": "p7",
    "name": "Camera Hikvision 4MP",
    "price": 1070000,
    "description": "Camera Hikvision 4MP — mô tả ngắn cho sản phẩm Camera Hikvision 4MP.",
    "image": "Camera/Camera ip 2mp hikvision DS-2CD1327G2-LUF.png",
    "sku": "SKU-P7",
    "warranty": "12 tháng",
    "category": "Camera & CCTV"
  },
  "p8": {
    "id": "p8",
    "name": "Camera IMOU 3MP",
    "price": 1080000,
    "description": "Camera IMOU 3MP — mô tả ngắn cho sản phẩm Camera IMOU 3MP.",
    "image": "Camera/Camera ip 2mp hikvision DS-2CD2723G2-LIZS2U.png",
    "sku": "SKU-P8",
    "warranty": "12 tháng",
    "category": "Camera & CCTV"
  },
  "p9": {
    "id": "p9",
    "name": "Camera Ngụy Trang",
    "price": 1090000,
    "description": "Camera Ngụy Trang — mô tả ngắn cho sản phẩm Camera Ngụy Trang.",
    "image": "Camera/Camera IPC-S2XP-10M0WED (Ranger Dual 10MP).png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P9",
    "warranty": "12 tháng",
    "category": "Camera & CCTV"
  },
  "p10": {
    "id": "p10",
    "name": "Camera WiFi 2MP",
    "price": 1100000,
    "description": "Camera WiFi 2MP — mô tả ngắn cho sản phẩm Camera WiFi 2MP.",
    "image": "Camera/Camera IPC-A32EP (Ranger 2, 3MP).png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P10",
    "warranty": "12 tháng",
    "category": "Camera & CCTV"
  },
  "p11": {
    "id": "p11",
    "name": "Camera AHD 2MP",
    "price": 1110000,
    "description": "Camera AHD 2MP — mô tả ngắn cho sản phẩm Camera AHD 2MP.",
    "image": "Camera/Camera IPC-C22FP-C (Versa).png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P11",
    "warranty": "12 tháng",
    "category": "Camera & CCTV"
  },
  "p12": {
    "id": "p12",
    "name": "Module IR LED",
    "price": 1120000,
    "description": "Module IR LED — mô tả ngắn cho sản phẩm Module IR LED.",
    "image": "Camera/Camera IPC-S3EP-5M0WE (Bullet 3 5MP).png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P12",
    "warranty": "12 tháng",
    "category": "Camera & CCTV"
  },
  "p13": {
    "id": "p13",
    "name": "Máy khoan pin 18V",
    "price": 1130000,
    "description": "Máy khoan pin 18V — mô tả ngắn cho sản phẩm Máy khoan pin 18V.",
    "image": "Khoan Pin/WF-ID1370BL.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P13",
    "warranty": "6 tháng",
    "category": "Máy khoan Pin"
  },
  "p14": {
    "id": "p14",
    "name": "Máy khoan pin 12V",
    "price": 1140000,
    "description": "Máy khoan pin 12V — mô tả ngắn cho sản phẩm Máy khoan pin 12V.",
    "image": "Khoan Pin/WF-ID1395BL.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P14",
    "warranty": "6 tháng",
    "category": "Máy khoan Pin"
  },
  "p15": {
    "id": "p15",
    "name": "Máy mài góc pin",
    "price": 1150000,
    "description": "Máy mài góc pin — mô tả ngắn cho sản phẩm Máy mài góc pin.",
    "image": "Khoan Pin/WF-AG100B-1.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P15",
    "warranty": "6 tháng",
    "category": "Máy khoan Pin"
  },
  "p16": {
    "id": "p16",
    "name": "Bộ pin 2Ah",
    "price": 1160000,
    "description": "Bộ pin 2Ah — mô tả ngắn cho sản phẩm Bộ pin 2Ah.",
    "image": "Khoan Pin/WF-AG100 MINI.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P16",
    "warranty": "6 tháng",
    "category": "Máy khoan Pin"
  },
  "p17": {
    "id": "p17",
    "name": "Sạc nhanh 18V",
    "price": 1170000,
    "description": "Sạc nhanh 18V — mô tả ngắn cho sản phẩm Sạc nhanh 18V.",
    "image": "Khoan Pin/WF-BK2006A.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P17",
    "warranty": "6 tháng",
    "category": "Máy khoan Pin"
  },
  "p18": {
    "id": "p18",
    "name": "Máy khoan động lực",
    "price": 1180000,
    "description": "Máy khoan động lực — mô tả ngắn cho sản phẩm Máy khoan động lực.",
    "image": "Khoan Pin/WF-ID13100AK (2).png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P18",
    "warranty": "6 tháng",
    "category": "Máy khoan Pin"
  },
  "p19": {
    "id": "p19",
    "name": "Bộ mũi khoan 50pcs",
    "price": 1190000,
    "description": "Bộ mũi khoan 50pcs — mô tả ngắn cho sản phẩm Bộ mũi khoan 50pcs.",
    "image": "Khoan Pin/WF-SDB10.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P19",
    "warranty": "6 tháng",
    "category": "Máy khoan Pin"
  },
  "p20": {
    "id": "p20",
    "name": "Máy khoan không chổi than",
    "price": 1200000,
    "description": "Máy khoan không chổi than — mô tả ngắn cho sản phẩm Máy khoan không chổi than.",
    "image": "Khoan Pin/WF-AG9000 PRO-1.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P20",
    "warranty": "6 tháng",
    "category": "Máy khoan Pin"
  },
  "p21": {
    "id": "p21",
    "name": "Máy khoan mini cầm tay",
    "price": 310000,
    "description": "Máy khoan mini cầm tay — mô tả ngắn cho sản phẩm Máy khoan mini cầm tay.",
    "image": "Khoan Pin/WF-RH3003PRO-1.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P21",
    "warranty": "6 tháng",
    "category": "Máy khoan Pin"
  },
  "p22": {
    "id": "p22",
    "name": "Vít điện 12V",
    "price": 1220000,
    "description": "Vít điện 12V — mô tả ngắn cho sản phẩm Vít điện 12V.",
    "image": "Khoan Pin/WF-SD150N.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P22",
    "warranty": "6 tháng",
    "category": "Máy khoan Pin"
  },
  "p23": {
    "id": "p23",
    "name": "Kềm đa năng",
    "price": 1230000,
    "description": "Kềm đa năng — mô tả ngắn cho sản phẩm Kềm đa năng.",
    "image": "Khoan Pin/WF-RH2203.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P23",
    "warranty": "6 tháng",
    "category": "Máy khoan Pin"
  },
  "p24": {
    "id": "p24",
    "name": "Bàn mài",
    "price": 1240000,
    "description": "Bàn mài — mô tả ngắn cho sản phẩm Bàn mài.",
    "image": "Khoan Pin/WF-PW3825BL.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P24",
    "warranty": "6 tháng",
    "category": "Máy khoan Pin"
  },
  "p25": {
    "id": "p25",
    "name": "Laptop Workstation 15\"",
    "price": 1250000,
    "description": "Laptop Workstation 15\" — mô tả ngắn cho sản phẩm Laptop Workstation 15\".",
    "image": "PC/Dell Insprio 15 inh.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P25",
    "warranty": "12 tháng",
    "category": "Máy tính & Laptop"
  },
  "p26": {
    "id": "p26",
    "name": "Laptop văn phòng 14\"",
    "price": 1260000,
    "description": "Laptop văn phòng 14\" — mô tả ngắn cho sản phẩm Laptop văn phòng 14\".",
    "image": "PC/Dell Vostro 3530 - i3-1305U 16GB  512GB SSD15.6 .png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P26",
    "warranty": "12 tháng",
    "category": "Máy tính & Laptop"
  },
  "p27": {
    "id": "p27",
    "name": "Mini PC i5",
    "price": 370000,
    "description": "Mini PC i5 — mô tả ngắn cho sản phẩm Mini PC i5.",
    "image": "PC/Dell Vostro 3530 i5-1334U16GB512GB SSD15.6 .png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P27",
    "warranty": "12 tháng",
    "category": "Máy tính & Laptop"
  },
  "p28": {
    "id": "p28",
    "name": "PC Gaming RTX 3060",
    "price": 1280000,
    "description": "PC Gaming RTX 3060 — mô tả ngắn cho sản phẩm PC Gaming RTX 3060.",
    "image": "PC/Dell Vostro 3530 i5-1334U8GB512GB SSD15.6 .png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P28",
    "warranty": "12 tháng",
    "category": "Máy tính & Laptop"
  },
  "p29": {
    "id": "p29",
    "name": "Laptop mỏng nhẹ",
    "price": 1290000,
    "description": "Laptop mỏng nhẹ — mô tả ngắn cho sản phẩm Laptop mỏng nhẹ.",
    "image": "PC/MTXT ASUS EXPERTBOOK B1402CVA-NK0062W i5-1335U8GB512G SSDFPWin11Xanh Đen14.0 FV.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P29",
    "warranty": "12 tháng",
    "category": "Máy tính & Laptop"
  },
  "p30": {
    "id": "p30",
    "name": "All-in-one 24\"",
    "price": 1300000,
    "description": "All-in-one 24\" — mô tả ngắn cho sản phẩm All-in-one 24\".",
    "image": "PC/MTXT DELL INS 3520 i5-1235U8GB512GB SSD15.6FHDWIN11+OFFICE BẠC N3520-i5U085W11SLU FV.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P30",
    "warranty": "12 tháng",
    "category": "Máy tính & Laptop"
  },
  "p31": {
    "id": "p31",
    "name": "Laptop đồ họa 16\"",
    "price": 1310000,
    "description": "Laptop đồ họa 16\" — mô tả ngắn cho sản phẩm Laptop đồ họa 16\".",
    "image": "PC/MTXT HP 15-fd0237TU Core i5-1334U,8GB RAM,512GB SSD,Intel Graphics,15.6.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P31",
    "warranty": "12 tháng",
    "category": "Máy tính & Laptop"
  },
  "p32": {
    "id": "p32",
    "name": "Laptop ASUS Vivobook",
    "price": 1320000,
    "description": "Laptop ASUS Vivobook — mô tả ngắn cho sản phẩm Laptop ASUS Vivobook.",
    "image": "PPC/MTXT LENOVO V15 G4 IRU i5-13420H8GD4512GSSD15.6FHDWLBT2CNoOS2Y_83A100F3VN.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P32",
    "warranty": "12 tháng",
    "category": "Máy tính & Laptop"
  },
  "p33": {
    "id": "p33",
    "name": "Laptop Dell Inspiron",
    "price": 1330000,
    "description": "Laptop Dell Inspiron — mô tả ngắn cho sản phẩm Laptop Dell Inspiron.",
    "image": "PC/Dell Vostro 3530 i5-1334U16GB512GB SSD15.6 .png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P33",
    "warranty": "12 tháng",
    "category": "Máy tính & Laptop"
  },
  "p34": {
    "id": "p34",
    "name": "Laptop Lenovo ThinkPad",
    "price": 1340000,
    "description": "Laptop Lenovo ThinkPad — mô tả ngắn cho sản phẩm Laptop Lenovo ThinkPad.",
    "image": "PC/Dell Insprio 15 inh.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P34",
    "warranty": "12 tháng",
    "category": "Máy tính & Laptop"
  },
  "p35": {
    "id": "p35",
    "name": "Bàn phím cơ",
    "price": 1350000,
    "description": "Bàn phím cơ — mô tả ngắn cho sản phẩm Bàn phím cơ.",
    "image": "PC/MTXT DELL INS 3520 i5-1235U8GB512GB SSD15.6FHDWIN11+OFFICE BẠC N3520-i5U085W11SLU FV.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P35",
    "warranty": "12 tháng",
    "category": "Máy tính & Laptop"
  },
  "p36": {
    "id": "p36",
    "name": "Màn hình 24\" FullHD",
    "price": 1360000,
    "description": "Màn hình 24\" FullHD — mô tả ngắn cho sản phẩm Màn hình 24\" FullHD.",
    "image": "PC/MTXT HP 15-fd0237TU Core i5-1334U,8GB RAM,512GB SSD,Intel Graphics,15.6.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P36",
    "warranty": "12 tháng",
    "category": "Máy tính & Laptop"
  },
  "p37": {
    "id": "p37",
    "name": "SSD 1TB",
    "price": 1370000,
    "description": "SSD 1TB — mô tả ngắn cho sản phẩm SSD 1TB.",
    "image": "linh kiện/SSD-1TB.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P37",
    "warranty": "6 tháng",
    "category": "Linh kiện"
  },
  "p38": {
    "id": "p38",
    "name": "HDD 2TB",
    "price": 1380000,
    "description": "HDD 2TB — mô tả ngắn cho sản phẩm HDD 2TB.",
    "image": "linh kiện/Ổ cứng WD Purple 2TB WD22PURZ.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P38",
    "warranty": "6 tháng",
    "category": "Linh kiện"
  },
  "p39": {
    "id": "p39",
    "name": "RAM 16GB DDR4",
    "price": 1390000,
    "description": "RAM 16GB DDR4 — mô tả ngắn cho sản phẩm RAM 16GB DDR4.",
    "image": "linh kiện/ram-16gb.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P39",
    "warranty": "6 tháng",
    "category": "Linh kiện"
  },
  "p40": {
    "id": "p40",
    "name": "Nguồn 500W",
    "price": 1400000,
    "description": "Nguồn 500W — mô tả ngắn cho sản phẩm Nguồn 500W.",
    "image": "linh kiện/DDR4 LAPTOP 4G2666 KINGMAX New Chính hãng .png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P40",
    "warranty": "6 tháng",
    "category": "Linh kiện"
  },
  "p41": {
    "id": "p41",
    "name": "Mainboard Intel",
    "price": 1410000,
    "description": "Mainboard Intel — mô tả ngắn cho sản phẩm Mainboard Intel.",
    "image": "linh kiện/Gigabit Multi-mode Media Converter TP-LINK MC200CM.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P41",
    "warranty": "6 tháng",
    "category": "Linh kiện"
  },
  "p42": {
    "id": "p42",
    "name": "VGA 8GB",
    "price": 1420000,
    "description": "VGA 8GB — mô tả ngắn cho sản phẩm VGA 8GB.",
    "image": "linh kiện/Thẻ nhớ Imou 64GB.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P42",
    "warranty": "6 tháng",
    "category": "Linh kiện"
  },
  "p43": {
    "id": "p43",
    "name": "Adapter 19V",
    "price": 1430000,
    "description": "Adapter 19V — mô tả ngắn cho sản phẩm Adapter 19V.",
    "image": "linh kiện/Switch poe 16 cổng hikvision DS-3E1518P-EI.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P43",
    "warranty": "6 tháng",
    "category": "Linh kiện"
  },
  "p44": {
    "id": "p44",
    "name": "Case ATX",
    "price": 1440000,
    "description": "Case ATX — mô tả ngắn cho sản phẩm Case ATX.",
    "image": "linh kiện/Switch poe 8 cổng hikvision DS-3E1510P-EI.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P44",
    "warranty": "6 tháng",
    "category": "Linh kiện"
  },
  "p45": {
    "id": "p45",
    "name": "Cooler CPU",
    "price": 1450000,
    "description": "Cooler CPU — mô tả ngắn cho sản phẩm Cooler CPU.",
    "image": "linh kiện/Thẻ nhớ Sandisk 256GB.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P45",
    "warranty": "6 tháng",
    "category": "Linh kiện"
  },
  "p46": {
    "id": "p46",
    "name": "Cable SATA",
    "price": 1460000,
    "description": "Cable SATA — mô tả ngắn cho sản phẩm Cable SATA.",
    "image": "linh kiện/Ổ cứng WD Purple 4TB WD42PURZ.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P46",
    "warranty": "6 tháng",
    "category": "Linh kiện"
  },
  "p47": {
    "id": "p47",
    "name": "M.2 Heatsink",
    "price": 1470000,
    "description": "M.2 Heatsink — mô tả ngắn cho sản phẩm M.2 Heatsink.",
    "image": "linh kiện/DDR5 LAPTOP 8G4800 HYNIX, KINGTON, SAMSUNG, MICRON.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P47",
    "warranty": "6 tháng",
    "category": "Linh kiện"
  },
  "p48": {
    "id": "p48",
    "name": "Fan 120mm",
    "price": 580000,
    "description": "Fan 120mm — mô tả ngắn cho sản phẩm Fan 120mm.",
    "image": "linh kiện/Ổ cứng WD Purple 3TB WD30PURZ.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P48",
    "warranty": "6 tháng",
    "category": "Linh kiện"
  },
  "p49": {
    "id": "p49",
    "name": "Wifi TP-Link TL-WR845N ",
    "price": 1490000,
    "description": "Wifi TP-Link TL-WR845N Chính hãng (3 anten 5dBi, 300Mbps, Repeater, 4LAN).",
    "image": "Network/Wifi TP-Link TL-WR845N Chính hãng (3 anten 5dBi, 300Mbps, Repeater, 4LAN).png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P49",
    "warranty": "12 tháng",
    "category": "Thiết bị mạng"
  },
  "p50": {
    "id": "p50",
    "name": "Wifi TP-Link EAP245",
    "price": 1500000,
    "description": "Wifi TP-Link EAP245 Chính hãng.",
    "image": "Network/Wifi TP-Link EAP245 Chính hãng.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P50",
    "warranty": "12 tháng",
    "category": "Thiết bị mạng"
  },
  "p51": {
    "id": "p51",
    "name": "Wifi TP-Link Archer C80 Chính hãng ",
    "price": 1510000,
    "description": "Wifi TP-Link Archer C80 Chính hãng  (4 anten, 1900Mbps, 2 băng tần, 4LAN 1Gbps).",
    "image": "Network/Wifi TP-Link Archer C80 Chính hãng  (4 anten, 1900Mbps, 2 băng tần, 4LAN 1Gbps).png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P51",
    "warranty": "12 tháng",
    "category": "Thiết bị mạng"
  },
  "p52": {
    "id": "p52",
    "name": "Router Wifi 4G LTE TPLink TL-MR100.",
    "price": 2520000,
    "description": "Router Wifi 4G LTE TPLink TL-MR100  (2 anten - 32 user - 2 port).",
    "image": "Network/Router Wifi 4G LTE TPLink TL-MR100  (2 anten - 32 user - 2 port).png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P52",
    "warranty": "12 tháng",
    "category": "Thiết bị mạng"
  },
  "p53": {
    "id": "p53",
    "name": "Router Wi-Fi 6 — AX3000.",
    "price": 2530000,
    "description": "Router Wi-Fi 6 — AX3000.",
    "image": "Network/Router Wi-Fi 6 — AX3000.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P53",
    "warranty": "12 tháng",
    "category": "Thiết bị mạng"
  },
  "p54": {
    "id": "p54",
    "name": "Router Cân bằng tải Gigabit Dual-WAN DRAYTEK VIGOR 2915 Chính hãng.",
    "price": 5540000,
    "description": "Router Cân bằng tải Gigabit Dual-WAN DRAYTEK VIGOR 2915 Chính hãng.",
    "image": "Network/Router Cân bằng tải Gigabit Dual-WAN DRAYTEK VIGOR 2915 Chính hãng.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P54",
    "warranty": "12 tháng",
    "category": "Thiết bị mạng"
  },
  "p55": {
    "id": "p55",
    "name": "DRAYTEK-2927.",
    "price": 4550000,
    "description": "Thiết bị cân bằng tải DRAYTEK-2927.",
    "image": "Network/DRAYTEK-2927.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P55",
    "warranty": "12 tháng",
    "category": "Thiết bị mạng"
  },
  "p56": {
    "id": "p56",
    "name": "AX5400 Ceiling Mount WiFi 6 Access Point TP-LINK EAP670.",
    "price": 1560000,
    "description": "AX5400 Ceiling Mount WiFi 6 Access Point TP-LINK EAP670.",
    "image": "Network/AX5400 Ceiling Mount WiFi 6 Access Point TP-LINK EAP670.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P56",
    "warranty": "12 tháng",
    "category": "Thiết bị mạng"
  },
  "p57": {
    "id": "p57",
    "name": "AX1800 Wireless Dual Band Access Point TP-LINK EAP610.",
    "price": 1570000,
    "description": "AX1800 Wireless Dual Band Access Point TP-LINK EAP610.",
    "image": "Network/AX1800 Wireless Dual Band Access Point TP-LINK EAP610.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P57",
    "warranty": "12 tháng",
    "category": "Thiết bị mạng"
  },
  "p58": {
    "id": "p58",
    "name": "AX1500 Wi-Fi 6 Router TP-LINK Archer AX12",
    "price": 1580000,
    "description": "AX1500 Wi-Fi 6 Router TP-LINK Archer AX12.",
    "image": "Network/AX1500 Wi-Fi 6 Router TP-LINK Archer AX12.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P58",
    "warranty": "12 tháng",
    "category": "Thiết bị mạng"
  },
  "p59": {
    "id": "p59",
    "name": "AC1200 Wireless Gigabit Router TP-LINK Archer C6 V2.0",
    "price": 1590000,
    "description": "AC1200 Wireless Gigabit Router TP-LINK Archer C6 V2.0.",
    "image": "Network/AC1200 Wireless Gigabit Router TP-LINK Archer C6 V2.0.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P59",
    "warranty": "12 tháng",
    "category": "Thiết bị mạng"
  },
  "p60": {
    "id": "p60",
    "name": "AC867 Access Point TP-LINK EAP215-Bridge KIT.",
    "price": 1600000,
    "description": "AC867 Access Point TP-LINK EAP215-Bridge KIT.",
    "image": "Network/5GHz AC867 Access Point TP-LINK EAP215-Bridge KIT.png",
    "detail": "• 2 Ống kính 6.0MP (3MP cố định + 3MP quay quét)\n• Ống kính cố định xoay cơ 0~260°, nghiêng 0~25°, tiêu cự 3.6mm (80°)\n• Ống kính PTZ xoay 0~355° ngang, 0~90° dọc, điều khiển từ xa\n• Hồng ngoại + LED thông minh, tầm xa 30m với 4 chế độ đêm\n• Đàm thoại 2 chiều, chống ồn\n• Cảnh báo chủ động: còi 110dB + đèn chớp xanh đỏ\n• IMOU SENSE AI: phát hiện người, theo dõi chuyển động\n• Wi-Fi 6 + cổng LAN, hỗ trợ ONVIF\n• Khe thẻ nhớ Micro SD 512GB\n• Nguồn 12V1A, công suất <12W",
    "sku": "SKU-P60",
    "warranty": "12 tháng",
    "category": "Thiết bị mạng"
  }
};
